CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "A Poké Flute awakens sleeping\n"
    .string "Pokémon. You know that.\p"
    .string "It does so with a sound that only\n"
    .string "they can hear.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "I rode here from Fuschia.\p"
    .string "It's an uphill ride on the\n"
    .string "Cycling Road, so I'm exhausted.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "If I had a bike, I would go to\n"
    .string "the Cycling Road!$"

