@ The museum now provides free entry so this stuff now goes unused
PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Yes, yes.\n"
    .string "It's ¥50 for a child's ticket.\p"
    .string "Would you like to come in?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Come again!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Right, ¥50!\n"
    .string "Thank you!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "You don't have enough money.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Welcome to the Pewter City Museum.\n"
    .string "Entry is free today.\p"
    .string "Please enjoy yourself.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "You can't sneak in the back way!\n"
    .string "Nice try, kid, but no.\p"
    .string "Oh, whatever!\n"
    .string "Do you know what amber is?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "Amber contains the genetic matter\n"
    .string "of ancient Pokémon.\p"
    .string "There's a lab somewhere trying to\n"
    .string "resurrect Pokémon from amber.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "Amber is actually sap, that gooey\n"
    .string "stuff that oozes from trees.\p"
    .string "The ancient sap fossilized over\n"
    .string "time to become rock-hard amber.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "I should be grateful for my long\n"
    .string "life.\p"
    .string "Never did I think I would get to\n"
    .string "see the bones of a dragon!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "Ssh! Listen, I need to share a\n"
    .string "secret with someone.\p"
    .string "I think that this chunk of amber\n"
    .string "contains Pokémon DNA!\p"
    .string "It would be a shattering scientific\n"
    .string "breakthrough if Pokémon could be\l"
    .string "resurrected from it.\p"
    .string "But, my colleagues just ignore\n"
    .string "what I have to say.\p"
    .string "So, I have a favor to ask!\p"
    .string "I want you to get this examined at\n"
    .string "a Pokémon Lab somewhere.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER} received the Old Amber\n"
    .string "from the man.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Ssh!\n"
    .string "Get the Old Amber checked!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "We have two fossils of rare,\n"
    .string "prehistoric Pokémon on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "There is a beautiful piece of\n"
    .string "Amber in a clear gold color.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "Aerodactyl Fossil\n"
    .string "A long-extinct POKéMON.\p"
    .string "Thanks to its rock-hard skull,\n"
    .string "it could use risky moves without.\p"
    .string "hurting itself.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "Kabutops Fossil\n"
    .string "A primitive and rare Pokémon.\p"
    .string "An apex predator, it can use its\n"
    .string "incredibly sharp scythes to slice\p"
    .string "through prey and drain their fluids.\n"
    .string "It was extinct until very recently,\p"
    .string "but its pre-evolved form Kabuto\n"
    .string "was just revived at Cinnabar Island.$"

