@ The idea is that Game Freak have become depressed as a resault of having to make essentially the exact same game every single year. This also means that the quality has plummeted in order to meet Nintendo and TPCi's deadline.
@ Showing the Game Director a Moltress will reignite their passion and ambition for game development... so they end up planning to offload the franchise onto ILCA. Oops.

CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Me? I'm the programmer!\p"
    .string "I'm getting laid off soon 'cause\n"
    .string "OpenAI just bribed the boss.\n"
    

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "I'm the graphic artist. I have spent\n"
    .string "the last decade making monster designs.\p"
    .string "Because of publisher mandates, I am to\n"
    .string "make more marketable monster designs.$"
    .string "The boss says those humanoid ones\n"
    .string "sell way more merch than the others.\n"
    
@ The "no-life" is me
CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "I wrote the story!\p"
    .string "I sure hope some no-life doesn't\n"
    .string "ruin all my hard work with bad jokes!$"

@ Showing this NPC a Moltress should reignite the devteam's heart and net you a good TM.    
CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "I'm the game designer…\p"
    .string "Our publisher requires us to make\n"
    .string "a new game in our series every year.\p"
    .string "We've got quotas to meet and deadlines\n"
    .string "to beat, so we're cutting corners.\p"
    .string "I guess it's worth it since all our\n"
    .string "releases are chart toppers…\p"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex_Old::
    .string "Is that right?\p"
    .string "I'm the game designer!\p"
    .string "Filling up your POKéDEX is tough,\n"
    .string "but don't quit!\p"
    .string "When you finish, come tell me!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Wow! Excellent!\n"
    .string "You completed your Pokédex!\l"
    .string "Congratulations!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "It's the game program! It looks\n"
    .string "highly unstable!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Someone's doomscrolling social media\n"
    .string "instead of working!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "It's the script!\n"
    .string "It's basically the same as always.$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "Game Freak Development Room$"

