VictoryRoad_2F_Text_DawsonIntro::
    .string "There is a super rare Pokémon\n"
    .string "up ahead. It's mine!$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "No!\n"
    .string "Unbelievable!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "Fine then, you go catch it.\n"
    .string "I'll just sulk over here.$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "This here is Victroy Road.\n"
    .string "It's the final test for Trainers!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Atcho!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "I'm certain that I saw a strange\n"
    .string "bird around here somewhere...$"

@ Maybe a stock Moltress looking like a rubber chicken is too on the nose...
VictoryRoad_2F_Text_NelsonIntro::
    .string "Hey, you. Seen any spicy chickens\n"
    .string "around here recently?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "I'm starving!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} also came through here.$"
    .string "He hadn't seen one either.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "Come on!\n"
    .string "I'll whip you!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "I got whipped!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "You earned the right to be on\n"
    .string "VICTORY ROAD…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "Is VICTORY ROAD too tough?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "Well done!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Many TRAINERS give up their\n"
    .string "challenge here and go home.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"

