@ I am not apologising for any of this

Text_RolloutTeach::
    .string "When you've got places to go,\n"
    .string "Rollout's your rainbow!\p"
    .string "Trust in me?$"

Text_RolloutDeclined::
    .string "I'll make it though!\n"
    .string "I'll prove it to you!$"

Text_RolloutWhichMon::
    .string "Who wants to roll around at\n"
    .string "the speed of sound?$"

Text_RolloutTaught::
    .string "You shouldn't care what lies ahead.\n"
    .string "Follow your plan instead!$"

