ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.\p"
    .string "You can also find some useful\n"
    .string  "services upstairs!$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "Pokémon Centers heal your tired,\n"
    .string "hurt, or fainted Pokémon.\p"
    .string "They make all Pokémon completely\n"
    .string "healthy.$"

