ViridianForest_Text_FriendsItchingToBattle::
    .string "I came here with some friends to\n"
    .string "catch us some Bug-type Pokémon!\p"
    .string "They're all itching to get into\n"
    .string "some Pokémon battles!$"

ViridianForest_Text_RickIntro::
    .string "Hey! You have Pokémon!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
    .string "No!\nCaterpie can't hack it!$"

ViridianForest_Text_RickPostBattle::
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "You can't jam out if you're a\l"
    .string "Pokémon Trainer!$"

ViridianForest_Text_DougDefeat::
    .string "Huh?\n"
    .string "I ran out of Pokémon!$"

ViridianForest_Text_DougPostBattle::
    .string "That totally stinks! I'm going to\n"
    .string "catch some stronger ones!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"

ViridianForest_Text_SammyDefeat::
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle::
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"

ViridianForest_Text_AnthonyIntro::
    .string "I might be little, but I won't like\n"
    .string "it if you go easy on me!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "I lost some of my allowance…$"

ViridianForest_Text_CharlieIntro::
    .string "My Pokémon knows a strong move!\n"
    .string "You can't win!$"

ViridianForest_Text_CharlieDefeat::
    .string "What!?\n"
    .string "I lost!$"

ViridianForest_Text_CharliePostBattle::
    .string "I should now offer to teach you\n"
    .string "Fury Cutter, but I don't yet$"

ViridianForest_Text_RanOutOfPokeBalls:: @ Now unused
    .string "I was throwing POKé BALLS to\n"
    .string "catch POKéMON, and I ran out.\p"
    .string "I should have tried one a\n"
    .string "many POKé BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TRAINER TIPS\p"
    .string "If your Pokémon are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "For poison, use an Antidote!\n"
    .string "Get it at Pokémon Marts!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "TRAINER TIPS\p"
    .string "Contact Prof. Oak via a PC to\n"
    .string "get your Pokédex evaluated!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRAINER TIPS\p"
    .string "You can't catch a Pokémon that\n"
    .string "belongs to someone else.\p"
    .string "Throw Poké Balls only at wild\n"
    .string "Pokémon to catch them!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "TRAINER TIPS\p"
    .string "Weaken Pokémon before attempting\n"
    .string "capture!\p"
    .string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"

Text_FuryCutterTeach::
    .string "I am a move tutor!\n"
    .string "I teach Fury Cutter.\p"
    .string "Someone should tell ShadowXeldron\n"
    .string "to give me real dialogue.\p"
    .string "Learn Fury Cutter?$"

Text_FuryCutterDeclined::
    .string "Awww... :($"

Text_FuryCutterWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Fury Cutter?$"

Text_FuryCutterTaught::
    .string "It's on the house, but in future\n"
    .string "builds I should gush about Cut Masters.$"
