PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "What!?\p"
    .string "Team Rocket is at Mt. Moon?\n"
    .string "Huh?\p"
    .string "I'm on the phone!\n"
    .string "Scram!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "Jigglypuff: Jiggly!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Yawn!\p"
    .string "When Jigglypuff sings, Pokémon get\n"
    .string "drowsy…\p"
    .string "…Me, too…\n"
    .string "Snore…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "I really want a Pikachu, so I'm\n"
    .string "trading my Clefairy for one.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "I'm trading Pokémon with that kid\n"
    .string "there.\p"
    .string "I had two Pikachu, so I figured\n"
    .string "I might as well trade one.$"

PewterCity_PokemonCenter_1F_Text_PokemonServices::
    .string "They now offer Pokemon services on the"
    .string "second floor of each Pokemon Center.\n"
    .string "You can re-learn or forget moves in any\p"
    .string "Pokemon Center, and they even have a name\p"
    .string "rater!\n"
    .string "But, I heard these new services put\p"
    .string "some people out of work...$"
