@ The Dream Eater tutor text used to be here but I moved it to Viridian City where it belongs. In its place there is a Mud-Slap tutor in Pewter City.
Text_MudSlapTeach::
    .string "I am a move tutor!\n"
    .string "I teach Mud-Slap.\p"
    .string "Someone should tell ShadowXeldron\n"
    .string "to give me real dialogue.\p"
    .string "Learn Mud-Slap?$"

Text_MudSlapDeclined::
    .string "Awww... :($"

Text_MudSlapWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Mud-Slap?$"

Text_MudSlapTaught::
    .string "In a later version of the hack,\n"
    .string "I will charge you ¥50 for this.$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "Clefairy came from the moon.\n"
    .string "That's what the rumor is.\p"
    .string "They appeared after Moon Stones\n"
    .string "fell on Mt. Moon.$"
    .string "Not only that, climbers have\n"
    .string "apparently heard a strange voice\p"
    .string "on the summit.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "There aren't many serious POKéMON\n"
    .string "TRAINERS here.\p"
    .string "They're all like BUG CATCHERS,\n"
    .string "you know, just hobbyists.\p"
    .string "But PEWTER GYM's BROCK isn't like\n"
    .string "that, not one bit.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Did you check out the Museum?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Weren't those fossils from Mt. Moon\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really?\n"
    .string "You absolutely have to go!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "This is it, the Museum.\p"
    .string "It's free to enter, so you have\n"
    .string "no excuse. See you around!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying PokéStinks to lure out\n"
    .string "some rare Pokémon!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "You're a Trainer, right?\p"
    .string "Brock's looking for new\n"
    .string "challengers. Follow me!$"

PewterCity_Text_GoTakeOnBrock::
    .string "If you have the right stuff,\n"
    .string "go take on Brock!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAINER TIPS\p"
    .string "All POKéMON that appear in battle,\n"
    .string "however briefly, earn EXP Points.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been stealing POKéMON\n"
    .string "fossils from Mt. Moon.\p"
    .string "Please call Officer Jenny if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid Pokémon Trainer!$"

PewterCity_Text_CitySign::
    .string "Pewter City\n"
    .string "A Stone Gray City$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I'm Prof. Oak's aide.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"

    @ TODO: Actually add Terastalisation
PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "Tera Orb from the aide!$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "You now weild the mystical power\n"
    .string "of the Terastal Phenomenon!$"

PewterCity_Text_ExplainRunningShoes::
    .string "Press the Select button mid-battle to\n"
    .string "change your Pokemon's to its Tera Type.\p"
    .string "But only once per battle!\n"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back to\n"
    .string "the lab.\p"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is a Tera Orb\n"
    .string "for my beloved challenger.\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"

