ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Whew! I'm trying to memorize all my\n"
    .string "notes.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Welcome to the Trainers' School!\p"
    .string "Here we teach budding trainers to be\n"
    .string "the very best like no one ever was.\p"
    .string "We also teach a couple of moves to\n"
    .string "certain Pokemon.\p"
    @ Remove these lines when fixed
    .string "WARNING: This menu is glitchy!\n"
    .string "do not open the help menu afterward!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "Defence Curl increases the user's\n"
    .string "Defence by one stage.\p"
    .string "Each stage of a stat increase improves\n"
    .string "that particular stat by around 50%.\p"
    .string "The move Rollout also becomes stronger\n"
    .string "if Defence Curl was used on the last turn.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "Psych Up copies the target's stat changes.\n"
    .string "It has a variety of interesting applications.\p"
    .string "For example, the move Swagger confuses the\n"
    .string "target and boosts their Attack by two stages.\p"
    .string "You can confuse an opponent with Swagger\n"
    .string "and then use Psych Up to boost your Attack.\p"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "Snore has a 30% chance to make the target\n" @ Part of me wanted to say "a useful move", but then I remembered that it's Snore
    .string "flinch, but it can only be used while asleep.\p"
    .string "It compliments the move Rest, which fully\n"
    .string "restores the user's HP but makes them fall\p"
    .string "asleep. You can use Rest to heal your Pokémon,\n"
    .string "then continue fighting with Snore.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fourth page…\p"
    .string "Finally, Endure is a tough move that\n"
    .string "will allow the user to survive a\p"
    .string "knockout blow on 1 HP.\n"
    .string "It pairs well with another move\n"
    .string "called Reversal, which gets much\p"
    .string "stronger when the user is low on\n"
    .string "HP.$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "GIRL: Hey!\n"
    .string "Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists POKéMON\n"
    .string "STATUS problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
    .string "A POKéMON can't attack if it's\n"
    .string "asleep.\p"
    .string "POKéMON will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"

ViridianCity_School_Text_ExplainBurn::
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
    .string "When poisoned, a POKéMON's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "A frozen POKéMON becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the POKéMON from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"

@ Move Tutor Stuff
ViridianCity_School_Text_MoveTaught::
    .string "Come again if there is anything\n"
    .string "you want to learn!$"
    
ViridianCity_School_Text_MoveDeclined::
    .string "That's okay. Come back if there\n"
    .string "is anything you want to learn.$"

Text_DefenceCurlTeach::
    .string "Teach Defence Curl?$"

Text_PsychUpTeach::
    .string "Teach Psych Up?$"

Text_SnoreTeach::
    .string "Teach Snore?$"

Text_EndureTeach::
    .string "Teach Endure?$"

Text_DefenceCurlWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Defence Curl?$"

Text_PsychUpWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Psych Up?$"

Text_SnoreWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Snore?$"

Text_EndureWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Endure?$"
