CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Hi!\n"
    .string "Welcome to our Bike Shop.\p"
    .string "Have we got just the bike for\n"
    .string "you!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Sorry!\n"
    .string "You can't afford it!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Oh, that's…\p"
    .string "A Bike Voucher!\p"
    .string "Okay!\n"
    .string "Here you go!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} exchanged the\n"
    .string "Bike Voucher for a Bicycle.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Thank you!\n"
    .string "Come back again sometime!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "How do you like your new Bicycle?\n"
    .string "Do you like how it rides?\p"
    .string "You can take it out on Cycling\n"
    .string "Road and even into caves!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "You better make room for your\n"
    .string "Bicycle!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "A plain city bike is good enough\n"
    .string "for me.\p"
    .string "After all, you can't put a shopping\n"
    .string "basket on a mountain bike.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "These bikes are cool, but they're\n"
    .string "way expensive!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Wow.\n"
    .string "Your bike is really cool!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "A shiny new bicycle!$"

@ New Xeldromix dialogue. This is intended to involve a sidequest where you show the guy an Electrode and will recieve a booster module for the bicycle that allows you to sprint on it similar to the Rotom Bike from SwSh.

CeruleanCity_BikeShop_Text_BoosterModQuestIntro::
    .string "How do you like your new Bicycle?\n"
    .string "Do you like how it rides?\p"
    .string "Hey, You collect Pokémon, right?\n"
    .string "Think you can do me a favour?\p"
    .string "I've been trying to figure out\n"
    .string "a way to make my bikes faster...\p"
    .string "But I just can't figure it out!\n"
    .string "I've heard that there's a\p"
    .string "Pokémon called Electrode. It is\n"
    .string "said to be the fastest there is.\p"
    .string "Problem is, I'm not so great at\n"
    .string "catching Pokémon.\p"
    .string "If you can show me one then I\n"
    .string "might just figure it out.\p"

CeruleanCity_BikeShop_Text_BoosterModQuestItsAnElectrode::
    .string "Hey! It's an Electrode! I've\n"
    .string "been looking for one of those.\p"
    .string "Could you let me borrow it\n"
    .string "for a bit?$"

CeruleanCity_BikeShop_Text_BoosterModQuestDeclined::
    .string "Oh, okay then. I'll keep looking\n"
    .string "for one then.$"

CeruleanCity_BikeShop_Text_BoosterModQuestWhyThanks::
    .string "Why, thanks! Wait there for a\n"
    .string "second...\p"

@ Fade to black...

CeruleanCity_BikeShop_Text_BoosterModQuestGetTheBooster::
    .string "Whoa! Electrode really is the\n"
    .string "fastest Pokemon on the planet!\p"
    .string "Here's Electrode back. Thank\n"
    .string "you for lending it to me!\p"
    .string "Also, with Electrode's help, I\n"
    .string "have made this new device.$"

@ You got the thing!

CeruleanCity_BikeShop_Text_BoosterModQuestItsAnAccelerator::
    .string "It's an Accel Unit! Hold down\n"
    .string "the B Button to blast off!\p"
    .string "Just.. hold on tight.\n"








