CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Hello!\n"
    .string "Welcome to Celadon Dept. Store!\p"
    .string "The board on the right describes\n"
    .string "the store layout.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: SERVICE COUNTER\p"
    .string "2F: TRAINER'S MARKET\p"
    .string "3F: VIDEO GAME SHOP\p"
    .string "4F: WISE MAN GIFTS\p"
    .string "5F: PHARMACY\p"
    .string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: SERVICE COUNTER$"

