CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "I got my Koffing from Cinnabar.\p"
    .string "It's usually nice, but it breathes\n"
    .string "poison when it's angry.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! This Gym is great!\n"
    .string "It's full of women!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "Celadon takes pride in its efforts\n"
    .string "to keep the city beautiful.\p"
    .string "That's why the new Game Corner is\n"
    .string "bad for our city's image.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Moan…\n"
    .string "I blew it all at the slots!\p"
    .string "I knew I should have cashed in my\n"
    .string "coins for prizes!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "This is my trusted pal, Poliwrath.\p"
    .string "It evolved from a Poliwhirl when\n"
    .string "I used a Water Stone.$"

CeladonCity_Text_Poliwrath::
    .string "Poliwrath: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "What are you staring at?\n"
    .string "Get lost, or I'll punch you.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Keep out of Team Rocket's way!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "Trainer Tips\p"
    .string "X Accuracy boosts the accuracy of\n"
    .string "techniques.\p"
    .string "Dire Hit jacks up the likelihood\n"
    .string "of critical hits.\p"
    .string "Get your items at the Celadon\n"
    .string "Department Store!$"

CeladonCity_Text_CitySign::
    .string "Celadon City\n"
    .string "The City of Rainbow Dreams$"

CeladonCity_Text_GymSign::
    .string "Celadon City Pokémon Gym\n"
    .string "Leader: Erika\l"
    .string "The Nature-Loving Princess!$"

CeladonCity_Text_MansionSign::
    .string "Celadon Condominiums$"

CeladonCity_Text_DeptStoreSign::
    .string "Find what you need at the\n"
    .string "Celadon Department Store!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "Trainer Tips\p"
    .string "Guard Spec. protects Pokémon\n"
    .string "from status-reduction moves during\l"
    .string "battle.\p"
    .string "Get your items at the\n"
    .string "Celadon Department Store!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "Coins exchanged for prizes!\n"
    .string "Prize Exchange$"

CeladonCity_Text_GameCornerSign::
    .string "Rocket Game Corner\n"
    .string "The playground for grown-ups!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaagh, ow…\n"
    .string "I scalded my tongue!\p"
    .string "This nice old lady in the\n"
    .string "Condominiums gave me some tea.\p"
    .string "But it was boiling hot!\n"
    .string "Gotta cool it to drink it.$"

Text_SoftboiledTeach::
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be good luck that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move Softboiled.$"

Text_SoftboiledDeclined::
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"

Text_SoftboiledWhichMon::
    .string "So, who's the Pokémon that gets\n"
    .string "the chance to learn Softboiled?$"

Text_SoftboiledTaught::
    .string "I wish you the best of luck!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Oh, what am I to do…\p"
    .string "Someone stole our Silph Scope.\p"
    .string "The thief came running this way,\n"
    .string "I'm sure of it.\p"
    .string "But I lost sight of him!\n"
    .string "Where'd he go?$"

@ Now for the self-deprecation. If it's okay for GF to insert themselves into the game then it's okay for me to do the same!
CeladonCity_Text_ShadowXeldronVoodooCurses::
    .string "You see that guy who is standing\p"
    .string "outside the Condodmiums?\n"
    .string "He's been muttering incomprehensible\p"
    .string "rubbish all day.\n"
    .string "Maybe he's trying to place a curse\p"
    .string "on the company that works there?\n"

CeladonCity_Text_ShadowXeldronGrimbleGrumble::
    .string "Grimble grimble grumble.\n"
    .string "No, YOU'RE a basketball! Stop\p"
    .string "being such a smelly stinker.\n"
    .string "Yeah, but, the thing is, moustaches\p"
    .string "are delicious.\n"

CeladonCity_Text_ShadowXeldronYouWantAFight::
    .string "Huh!? What!?\p"
    .string "You want a battle!?$"

CeladonCity_Text_ShadowXeldronOkay::
    .string "Okay.$"

CeladonCity_Text_ShadowXeldronWhatWasIDoing::
    .string "Anyway, what exactly was I doing\p"
    .string "again?$"
