ColourDungeon_Text_ImpassableBoulders::
    .string "It is an impassable boulder that is\p"
    .string "too heavy for even Strength to push.\n"
    .string "There must be some way to remove\p"
    .string "it...$"

ColourDungeon_Text_TrialSign::
    .string "To they who dare to enter, clear all\p"
    .string "secondary trials to find the prime.\n"
    .string "There you shall find the sleeping\p"
    .string "twins.$"
